[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "echo '=== cwd:'$(pwd)' ===' && ls .next/standalone/server.js && echo '=== starting on PORT='$PORT' ===' && HOSTNAME=0.0.0.0 node .next/standalone/server.js"

[[volumes]]
mountPath = "/data"
