[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npx prisma db push --skip-generate --accept-data-loss && HOSTNAME=0.0.0.0 node .next/standalone/server.js"

[[volumes]]
mountPath = "/data"
